import { Container, Spacer, Text } from '@nextui-org/react'
import Head from 'next/head'
import TitleText from '../components/TitleText'
import Layout from '../components/Layout'
import { CustomPopover } from '../components/CustomPopover'
import { CustomTextCell } from '../components/CustomTextCell'
//import {CustomCard} from '../components/CustomCard'


export default function Home() {
  return (
    <Layout>
      <Container fluid className='d-flex text-center w-100 flex-column min-vh-100 '  >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Text> Este va a ser mi landing page, aca voy a tener un hero, con una navbar, con mi titulo</Text>
        <Container fluid display='flex' alignItems='center' justify='center' className='hero' direction='column'>

        <TitleText title="Todo lo que necesitas, en LocasLopez!!"> Bienvenido a LocasLopez, tu tienda de ropa favorita, donde encontraras la mejor calidad a los mejores precios</TitleText>
        <Spacer y={6}/>
        <Text> Bienvenido a nuestra pagina principal, donde encontraras todo tipo de prendas </Text>
        <Spacer y={1}/>
        <CustomPopover title="Tenemos lo que necesitas"> Accesorios, pantalones, camperas, todo tipo de ropa de calidad a buen precio  </CustomPopover>
        </Container>
        <Spacer y={3}/>
        <TitleText title="Un solsticio de descuentos">Para celebrar la llegada de las vacaciones de invierno, tenemos descuentos de hasta el 50% en buzos, camperas y botas!</TitleText>
        <Spacer y={3}/>
        <Text weight={'extrabold'} size={'$2xl'}>[Zona en proceso de maquetado creativo y tecnologico, no pasar]</Text>
        <Spacer y={3}/>  
      </Container>
    </Layout>
  )
}
